import { DEFAULT_RULE_SET_ID, getRuleSet, isValidScore, type TRuleSetId } from "@/rules/ruleSets";
import { scoreDice } from "@/rules/scoreDice";
import type { ECategory, TDieValue } from "@/rules/types";
import { createDiceState, DICE_COUNT, MAX_ROLLS } from "./dice";
import { getCurrentPlayer } from "./selectors";
import type { IDiceState, IGameState, IPlayer } from "./types";

export type TGameAction =
  | { type: "NEW_GAME"; ruleSetId: TRuleSetId; playerNames: string[]; diceMode?: boolean }
  | { type: "SET_SCORE"; playerId: string; categoryId: ECategory; value: number }
  | { type: "CLEAR_SCORE"; playerId: string; categoryId: ECategory }
  | { type: "RESET" }
  | { type: "END_GAME" }
  /** Roll every die that is not held. The values are generated by the caller so the reducer stays pure. */
  | { type: "ROLL_DICE"; values: TDieValue[] }
  | { type: "TOGGLE_LOCK"; index: number }
  /** Score the current dice for the current player and start the next turn. */
  | { type: "SCORE_DICE"; categoryId: ECategory }
  /** Take back a SCORE_DICE: clear the cell and restore the dice as they were. */
  | { type: "UNDO_DICE_SCORE"; playerId: string; categoryId: ECategory; dice: IDiceState };

export function createInitialState(): IGameState {
  return { ruleSetId: DEFAULT_RULE_SET_ID, players: [] };
}

function updatePlayer(state: IGameState, playerId: string, update: (player: IPlayer) => IPlayer): IGameState {
  if (!state.players.some((p) => p.id === playerId)) return state;
  return {
    ...state,
    players: state.players.map((p) => (p.id === playerId ? update(p) : p)),
  };
}

function withoutScore(player: IPlayer, categoryId: ECategory): IPlayer {
  const sheet = { ...player.sheet };
  delete sheet[categoryId];
  return { ...player, sheet };
}

export function gameReducer(state: IGameState, action: TGameAction): IGameState {
  switch (action.type) {
    case "NEW_GAME": {
      const names = action.playerNames.map((n) => n.trim()).filter((n) => n.length > 0);
      if (names.length === 0) return state;
      const next: IGameState = {
        ruleSetId: action.ruleSetId,
        players: names.map((name, i) => ({ id: `player-${i + 1}`, name, sheet: {} })),
      };
      if (action.diceMode) next.dice = createDiceState();
      return next;
    }

    case "SET_SCORE": {
      if (!isValidScore(getRuleSet(state.ruleSetId), action.categoryId, action.value)) return state;
      return updatePlayer(state, action.playerId, (p) => ({
        ...p,
        sheet: { ...p.sheet, [action.categoryId]: action.value },
      }));
    }

    case "CLEAR_SCORE":
      return updatePlayer(state, action.playerId, (p) => withoutScore(p, action.categoryId));

    case "RESET": {
      const next: IGameState = { ...state, players: state.players.map((p) => ({ ...p, sheet: {} })) };
      if (state.dice) next.dice = createDiceState();
      return next;
    }

    case "END_GAME":
      return { ruleSetId: state.ruleSetId, players: [] };

    case "ROLL_DICE": {
      const { dice } = state;
      if (!dice || dice.rollsUsed >= MAX_ROLLS || action.values.length !== DICE_COUNT) return state;
      if (!getCurrentPlayer(state)) return state;
      const held = dice.rollsUsed > 0 ? dice.locked : dice.locked.map(() => false);
      return {
        ...state,
        dice: {
          values: action.values.map((value, i) => (held[i] ? dice.values[i] : value)),
          locked: held,
          rollsUsed: dice.rollsUsed + 1,
        },
      };
    }

    case "TOGGLE_LOCK": {
      const { dice } = state;
      if (!dice || dice.rollsUsed === 0 || dice.rollsUsed >= MAX_ROLLS) return state;
      if (action.index < 0 || action.index >= DICE_COUNT) return state;
      return {
        ...state,
        dice: { ...dice, locked: dice.locked.map((held, i) => (i === action.index ? !held : held)) },
      };
    }

    case "SCORE_DICE": {
      const { dice } = state;
      if (!dice || dice.rollsUsed === 0) return state;
      const player = getCurrentPlayer(state);
      const category = getRuleSet(state.ruleSetId).categories.find((c) => c.id === action.categoryId);
      if (!player || !category || player.sheet[category.id] !== undefined) return state;
      const value = scoreDice(category, dice.values);
      return {
        ...updatePlayer(state, player.id, (p) => ({ ...p, sheet: { ...p.sheet, [category.id]: value } })),
        dice: createDiceState(),
      };
    }

    case "UNDO_DICE_SCORE": {
      if (!state.dice) return state;
      return { ...updatePlayer(state, action.playerId, (p) => withoutScore(p, action.categoryId)), dice: action.dice };
    }
  }
}
